import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"
import TopBanner from "@/components/shared/TopBanner";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import AdmissionForm from "@/components/forms/AdmissionQuery";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          
      <section>
        <TopBanner />
        <Navbar/>
      </section>
      <AdmissionForm/>
        {children}
      <section>
        <Footer/>
      </section>
      </body>
    </html>
  );
}
